AR = ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar']
ARCH_ST = ['-arch']
ARFLAGS = ['rcs']
BINDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/bin'
BIN_PERL = ['/usr/bin/perl']
CC = ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'clang'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('13', '1', '6')
CFLAGS = ['-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator15.4.sdk', '-arch', 'x86_64', '-mtvos-version-min=13', '-fembed-bitcode', '-I/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/include', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_FILE_OFFSET_BITS=64', '-Wall', '-std=c11', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wimplicit-fallthrough', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-Wno-logical-op-parentheses', '-fcolor-diagnostics', '-Wno-tautological-compare', '-Wno-tautological-constant-out-of-range-compare']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
CFLAGS_libav_any = ['-pthread', '-pthread', '-pthread']
CFLAGS_libavcodec = ['-pthread', '-pthread']
CFLAGS_libavdevice = ['-pthread', '-pthread', '-pthread']
CFLAGS_libavutil = ['-pthread']
CFLAGS_pthreads = ['-pthread']
COMPILER_CC = 'clang'
CONFDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/etc/mpv'
CONFLOADDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/etc/mpv'
CPPPATH_ST = '-I%s'
CXXFLAGS_libav_any = ['-pthread', '-pthread', '-pthread']
CXXFLAGS_libavcodec = ['-pthread', '-pthread']
CXXFLAGS_libavdevice = ['-pthread', '-pthread', '-pthread']
CXXFLAGS_libavutil = ['-pthread']
DATADIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share'
DATAROOTDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share'
DEFINES = []
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'DEFAULT_DVD_DEVICE': '', 'DEFAULT_CDROM_DEVICE': '', 'HAVE_LGPL': '', 'HAVE_GPL': '', 'HAVE_CPLAYER': '', 'HAVE_LIBMPV_SHARED': '', 'HAVE_LIBMPV_STATIC': '', 'HAVE_STATIC_BUILD': '', 'HAVE_BUILD_DATE': '', 'HAVE_OPTIMIZE': '', 'HAVE_DEBUG_BUILD': '', 'HAVE_TESTS': '', 'HAVE_TA_LEAK_REPORT': '', 'HAVE_MANPAGE_BUILD': '', 'HAVE_HTML_BUILD': '', 'HAVE_PDF_BUILD': '', 'HAVE_LIBDL': '', 'HAVE_CPLUGINS': '', 'HAVE_ASM': '', 'HAVE_CLANG_DATABASE': '', 'HAVE_SWIFT_STATIC': '', 'HAVE_NOEXECSTACK': '', 'HAVE_LIBM': '', 'HAVE_MINGW': '', 'HAVE_POSIX': '', 'HAVE_ANDROID': '', 'HAVE_TVOS': '', 'HAVE_EGL_ANDROID': '', 'HAVE_POSIX_OR_MINGW': '', 'HAVE_SWIFT': '', 'HAVE_UWP': '', 'HAVE_WIN32_DESKTOP': '', 'HAVE_WIN32_INTERNAL_PTHREADS': '', 'HAVE_PTHREADS': '', 'HAVE_GNUC': '', 'HAVE_STDATOMIC': '', 'HAVE_ALIGNED_ALLOC': '', 'HAVE_ATOMICS': '', 'HAVE_LIBRT': '', 'HAVE_ICONV': '', 'HAVE_DOS_PATHS': '', 'HAVE_POSIX_SPAWN_NATIVE': '', 'HAVE_POSIX_SPAWN_ANDROID': '', 'HAVE_POSIX_SPAWN': '', 'HAVE_WIN32_PIPES': '', 'HAVE_GLOB_POSIX': '', 'HAVE_GLOB_WIN32': '', 'HAVE_GLOB': '', 'HAVE_FCHMOD': '', 'HAVE_VT_H': '', 'HAVE_GBM_H': '', 'HAVE_GLIBC_THREAD_NAME': '', 'HAVE_OSX_THREAD_NAME': '', 'HAVE_BSD_THREAD_NAME': '', 'HAVE_BSD_FSTATFS': '', 'HAVE_LINUX_FSTATFS': '', 'HAVE_MEMFD_CREATE': '', 'HAVE_LIBSMBCLIENT': '', 'HAVE_LUA': '', 'HAVE_JAVASCRIPT': '', 'HAVE_LIBASS': '', 'HAVE_LIBASS_OSD': '', 'HAVE_DUMMY_OSD': '', 'HAVE_ZLIB': '', 'HAVE_LIBBLURAY': '', 'HAVE_DVDNAV': '', 'HAVE_CDDA': '', 'HAVE_UCHARDET': '', 'HAVE_RUBBERBAND': '', 'HAVE_ZIMG': '', 'HAVE_LCMS2': '', 'HAVE_VAPOURSYNTH': '', 'HAVE_LIBARCHIVE': '', 'HAVE_DVBIN': '', 'HAVE_SDL2': '', 'HAVE_SDL2_GAMEPAD': '', 'HAVE_LIBAVCODEC': '', 'HAVE_LIBAVUTIL': '', 'HAVE_FFMPEG': '', 'HAVE_LIBAV': '', 'HAVE_LIBAV_ANY': '', 'HAVE_LIBAVDEVICE': '', 'HAVE_FFMPEG_STRICT_ABI': '', 'HAVE_SDL2_AUDIO': '', 'HAVE_OSS_AUDIO': '', 'HAVE_RSOUND': '', 'HAVE_SNDIO': '', 'HAVE_PULSE': '', 'HAVE_JACK': '', 'HAVE_OPENAL': '', 'HAVE_OPENSLES': '', 'HAVE_ALSA': '', 'HAVE_COREAUDIO': '', 'HAVE_AUDIOUNIT': '', 'HAVE_WASAPI': '', 'HAVE_SDL2_VIDEO': '', 'HAVE_COCOA': '', 'HAVE_DRM': '', 'HAVE_DRMPRIME': '', 'HAVE_GBM': '', 'HAVE_WAYLAND_SCANNER': '', 'HAVE_WAYLAND_PROTOCOLS': '', 'HAVE_WAYLAND': '', 'HAVE_X11': '', 'HAVE_XV': '', 'HAVE_GL_COCOA': '', 'HAVE_GL_X11': '', 'HAVE_EGL': '', 'HAVE_EGL_X11': '', 'HAVE_EGL_DRM': '', 'HAVE_GL_WAYLAND': '', 'HAVE_GL_WIN32': '', 'HAVE_GL_DXINTEROP': '', 'HAVE_EGL_ANGLE': '', 'HAVE_EGL_ANGLE_LIB': '', 'HAVE_EGL_ANGLE_WIN32': '', 'HAVE_VDPAU': '', 'HAVE_VDPAU_GL_X11': '', 'HAVE_VAAPI': '', 'HAVE_VAAPI_X11': '', 'HAVE_VAAPI_WAYLAND': '', 'HAVE_VAAPI_DRM': '', 'HAVE_VAAPI_X_EGL': '', 'HAVE_VAAPI_EGL': '', 'HAVE_CACA': '', 'HAVE_JPEG': '', 'HAVE_DIRECT3D': '', 'HAVE_SHADERC_SHARED': '', 'HAVE_SHADERC_STATIC': '', 'HAVE_SHADERC': '', 'HAVE_SPIRV_CROSS_SHARED': '', 'HAVE_SPIRV_CROSS_STATIC': '', 'HAVE_SPIRV_CROSS': '', 'HAVE_D3D11': '', 'HAVE_RPI': '', 'HAVE_IOS_GL': '', 'HAVE_PLAIN_GL': '', 'HAVE_GL': '', 'HAVE_LIBPLACEBO': '', 'HAVE_VULKAN': '', 'HAVE_VAAPI_VULKAN': '', 'HAVE_EGL_HELPERS': '', 'HAVE_VIDEOTOOLBOX_HWACCEL': '', 'HAVE_VIDEOTOOLBOX_GL': '', 'HAVE_D3D_HWACCEL': '', 'HAVE_D3D9_HWACCEL': '', 'HAVE_GL_DXINTEROP_D3D9': '', 'HAVE_FFNVCODEC': '', 'HAVE_CUDA_HWACCEL': '', 'HAVE_RPI_MMAL': '', 'HAVE_WIN32_EXECUTABLE': '', 'HAVE_MACOS_TOUCHBAR': '', 'HAVE_MACOS_10_11_FEATURES': '', 'HAVE_MACOS_10_12_2_FEATURES': '', 'HAVE_MACOS_10_14_FEATURES': '', 'HAVE_MACOS_MEDIA_PLAYER': '', 'HAVE_MACOS_COCOA_CB': '', 'CONFIGURATION': '', 'MPV_CONFDIR': '', 'FULLCONFIG': ''}
DEST_BINFMT = 'mac-o'
DEST_CPU = 'aarch64'
DEST_OS = 'darwin'
DOCDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
DVIDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
EXEC_PREFIX = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64'
FRAMEWORKPATH_ST = '-F%s'
FRAMEWORK_ST = ['-framework']
FRAMEWORK_audiounit = ['Foundation', 'AudioToolbox']
FRAMEWORK_libav_any = ['Metal', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
FRAMEWORK_libavcodec = ['VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
FRAMEWORK_libavdevice = ['Metal', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo', 'VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
FRAMEWORK_libavutil = ['VideoToolbox', 'CoreFoundation', 'CoreMedia', 'CoreVideo']
HAVE_ALIGNED_ALLOC = 1
HAVE_AUDIOUNIT = 1
HAVE_BSD_FSTATFS = 1
HAVE_CPLUGINS = 1
HAVE_DRMPRIME = 1
HAVE_FCHMOD = 1
HAVE_FFMPEG = 1
HAVE_GLOB_POSIX = 1
HAVE_GNUC = 1
HAVE_ICONV = 1
HAVE_IOS_GL = 1
HAVE_LIBAVCODEC = 1
HAVE_LIBAVDEVICE = 1
HAVE_LIBAVUTIL = 1
HAVE_LIBAV_ANY = 1
HAVE_LIBDL = 1
HAVE_LIBM = 1
HAVE_OSX_THREAD_NAME = 1
HAVE_POSIX = 1
HAVE_PTHREADS = 1
HAVE_STDATOMIC = 1
HAVE_TVOS = 1
HAVE_ZLIB = 1
HTMLDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
INCLUDEDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/include'
INCLUDES_libav_any = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/include']
INCLUDES_libavcodec = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/include']
INCLUDES_libavdevice = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/include']
INCLUDES_libavutil = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/include']
INFODIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/info'
LDFLAGS = ['-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator15.4.sdk', '-arch', 'x86_64', '-Wimplicit-function-declaration,13', '-lbz2', '-L/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/lib'
LIBEXECDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/libexec'
LIBPATH_ST = '-L%s'
LIBPATH_libav_any = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBPATH_libavcodec = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBPATH_libavdevice = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIBPATH_libavutil = ['/Users/ns/Documents/GitHub/playerPublic/contrib/FFmpeg-tvOS/thin/x86_64/lib']
LIB_ST = '-l%s'
LIB_iconv = ['iconv']
LIB_libav_any = ['avfilter', 'm', 'swscale', 'm', 'avformat', 'm', 'bz2', 'z', 'avcodec', 'iconv', 'm', 'swresample', 'm', 'avutil', 'm']
LIB_libavcodec = ['avcodec', 'iconv', 'm', 'swresample', 'm', 'avutil', 'm']
LIB_libavdevice = ['avdevice', 'm', 'avfilter', 'm', 'swscale', 'm', 'avformat', 'm', 'bz2', 'z', 'avcodec', 'iconv', 'm', 'swresample', 'm', 'avutil', 'm']
LIB_libavutil = ['avutil', 'm']
LIB_libm = ['m']
LIB_zlib = ['z']
LINKFLAGS = ['-rdynamic']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cplugins = ['-rdynamic']
LINKFLAGS_cshlib = ['-dynamiclib']
LINKFLAGS_cstlib = []
LINKFLAGS_libav_any = ['-pthread', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', '-pthread']
LINKFLAGS_libavcodec = ['-pthread', '-pthread']
LINKFLAGS_libavdevice = ['-pthread', '-Wl,-framework,CoreFoundation', '-Wl,-framework,Security', '-pthread', '-pthread']
LINKFLAGS_libavutil = ['-pthread']
LINK_CC = ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc']
LOCALEDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/locale'
LOCALSTATEDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/var'
MACOS_SDK = '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk'
MACOS_SDK_VERSION = '12.3'
MANDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/man'
OLDINCLUDEDIR = '/usr/include'
PACKAGE = 'mpv'
PDFDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
PKG_CONFIG = ['/opt/homebrew/bin/pkg-config']
PREFIX = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64'
PSDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/doc/mpv'
RPATH_ST = '-Wl,-rpath,%s'
SBINDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/sbin'
SHAREDSTATEDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/com'
SHLIB_MARKER = []
SONAME_ST = []
STLIBPATH_ST = '-L%s'
STLIB_MARKER = []
STLIB_ST = '-l%s'
SYSCONFDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/etc'
ZSHDIR = '/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/thin/x86_64/share/zsh/site-functions'
cfg_files = ['/Users/ns/Documents/GitHub/playerPublic/contrib/mpv-tvOS/scratch/x86_64/config.h']
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.dylib'
cstlib_PATTERN = 'lib%s.a'
define_key = []
known_deps = ['cuda-hwaccel', 'openal', 'vaapi', 'html-build', 'bsd-fstatfs', 'vaapi-wayland', 'vulkan', 'libbluray', 'dvbin', 'libavcodec', 'macos-10-12-2-features', 'ffnvcodec', 'dos-paths', 'rsound', 'wayland-protocols', 'oss-audio', 'posix-or-mingw', 'memfd_create', 'x11', 'libav-any', 'libmpv-shared', 'librt', 'gbm', 'ffmpeg-strict-abi', 'shaderc', 'sdl2-video', 'glibc-thread-name', 'plain-gl', 'swift-static', 'sdl2-audio', 'javascript', 'wayland-scanner', 'pthreads', 'win32-internal-pthreads', 'gnuc', 'posix-spawn-android', 'lua', 'vaapi-x-egl', 'uchardet', 'cocoa', 'build-date', 'jack', 'vaapi-egl', 'posix-spawn-native', 'direct3d', 'gbm.h', 'shaderc-static', 'win32-executable', 'lgpl', 'stdatomic', 'macos-10-11-features', 'cplugins', 'libavutil', 'os-darwin', 'bsd-thread-name', 'dvdnav', 'macos-cocoa-cb', 'sndio', 'drmprime', 'uwp', 'spirv-cross', 'coreaudio', 'vdpau', 'd3d-hwaccel', 'win32-desktop', 'rpi', 'egl-helpers', 'macos-media-player', 'drm', 'libdl', 'osx-thread-name', 'vapoursynth', 'd3d9-hwaccel', 'caca', 'posix-spawn', 'gl', 'swift', 'spirv-cross-shared', 'gl-dxinterop', 'android', 'pdf-build', 'libplacebo', 'manpage-build', 'zlib', 'wayland', 'egl-android', 'tvos', 'fchmod', 'egl-x11', 'clang-database', 'libass', 'sdl2', 'libav', 'pulse', 'spirv-cross-static', 'rpi-mmal', 'cplayer', 'dummy-osd', 'noexecstack', 'gl-win32', 'jpeg', 'gl-dxinterop-d3d9', 'glob-win32', 'ta-leak-report', 'sdl2-gamepad', 'egl-angle-win32', 'macos-touchbar', 'd3d11', 'vaapi-vulkan', 'libmpv-static', 'posix', 'aligned_alloc', 'vaapi-drm', 'audiounit', 'libsmbclient', 'optimize', 'rubberband', 'debug-build', 'iconv', 'xv', 'tests', 'zimg', 'egl', 'opensles', 'asm', 'glob', 'ffmpeg', 'vaapi-x11', 'wasapi', 'videotoolbox-gl', 'cdda', 'libm', 'gl-x11', 'vdpau-gl-x11', 'gl-cocoa', 'glob-posix', 'gl-wayland', 'egl-angle', 'alsa', 'libass-osd', 'macos-10-14-features', 'win32-pipes', 'ios-gl', 'mingw', 'egl-angle-lib', 'linux-fstatfs', 'vt.h', 'gpl', 'libavdevice', 'atomics', 'libarchive', 'egl-drm', 'lcms2', 'static-build', 'shaderc-shared', 'videotoolbox-hwaccel']
macbundle_PATTERN = '%s.bundle'
satisfied_deps = ['gnuc', 'tvos', 'fchmod', 'asm', 'build-date', 'bsd-fstatfs', 'glob', 'libavcodec', 'ffmpeg', 'dummy-osd', 'lgpl', 'stdatomic', 'libm', 'cplugins', 'libavutil', 'posix-or-mingw', 'os-darwin', 'glob-posix', 'drmprime', 'libmpv-static', 'posix', 'aligned_alloc', 'libav-any', 'audiounit', 'ios-gl', 'plain-gl', 'optimize', 'libdl', 'osx-thread-name', 'gl', 'libavdevice', 'atomics', 'debug-build', 'iconv', 'pthreads', 'videotoolbox-hwaccel', 'zlib']
